name: test-on-push-and-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run 'pr' target
      run: make pr

  amazonlinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run amazonlinux integration tests
      run: DISTRO=amazonlinux make test-integ